#
#   version 
#
###########################################
###########################################
#   SETUP WHERE IS THE linear algebra procedures
###########################################
###########################################
OPTIM = /ccc/work/cont003/gen10596/gen10596/svn/OPTIMIZATION

###########################################
# ENV SETUP intel compilers
#module load intel-compilers/19.0.4 intel-mpi/2019.4 intel-mkl/2019.4
###########################################

###########################################
# ENV SETUP FFTW library
###########################################
#module load fftw/3.3.8
FFTW3=${FFTW3_ROOT}
# or link with own libraries compiled from wind_codes/share/FFTW sources
#FFTW3=../../../../share/FFTW/fftw-3.3.8
FFTW3_LIB=${FFTW3}/lib
FFTW3_INC=${FFTW3}/include
###########################################

###########################################
###########################################
#   DONE     TENTATIVELY YOU SHOULD NOT MODIFY BELOW
###########################################
###########################################

RM = /bin/rm -f

CC =  mpicc 
FC =  mpif90 
FL =  mpif90 

F77 = mpif90 
F90 = mpif90 
ICC = mpicc 

AR = ar vr
RANLIB  = echo

#OPTIONS COMPILE
 
OPTF =  -O3 -assume byterecl -qopenmp
OPTC =  -O3 -assume byterecl -qopenmp
OPTL =  -O3 -assume byterecl -qopenmp

#DEBUG VERBEUX
#OPTF =  -assume byterecl -qopenmp -g -warn all
#OPTC =  -assume byterecl -qopenmp -g -warn all
#OPTL =  -assume byterecl -qopenmp -g -warn all

#DEBUG AGRESSIF
#OPTF =  -assume byterecl -qopenmp -g -traceback -check bounds -fp-stack-check -gen-interfaces -warn interfaces -check arg_temp_created
#OPTC =  -assume byterecl -qopenmp -g -traceback -check bounds -fp-stack-check -gen-interfaces -warn interfaces -check arg_temp_created
#OPTL =  -assume byterecl -qopenmp -g -traceback -check bounds -fp-stack-check -gen-interfaces -warn interfaces -check arg_temp_created

#DEBUG LIGHT

#OPTF =  -O2 -g -assume byterecl -qopenmp 
#OPTC =  -O2 -g -assume byterecl -qopenmp
#OPTL =  -O2 -g -assume byterecl -qopenmp


LOPTIM=-L$(OPTIM)/lib -lSEISCOPE_OPTIM
########################################################################
INCPAR = -I$(LIB)/COMMON/include -I../inc
##############################################################################

INCPAR =-I$(OPTIM)/COMMON/include -I../inc -I${FFTW3_INC}
LIBPAR=$(LOPTIM) -L${FFTW3_LIB} -lfftw3

#INCPAR =-I$(OPTIM)/COMMON/include -I../inc
#LIBPAR=$(LOPTIM) 


INC = $(INCPAR)
LIB = $(LIBPAR)

